name: .NET

on:
  pull_request:
    branches: [ main ]
    paths: 
     - 'apis/poi/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/poi
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test 'tests/UnitTests/UnitTests.csproj' --no-build --verbosity normal
    - name: The job has failed
      uses: stefanstranger/azuredevops-bug-action@1.1
      if: failure()
      with:
        OrganizationName: "hacker2fet"
        PAT: "PAT"
        ProjectName: "OpenHack"
        AreaPath: "OpenHack"
        IterationPath: "Iteration 1"
        GithubToken: "GithubToken"
        WorkflowFileName: "poi.yml"
      env:
        PAT: ${{ secrets.AZDOPAT}}
        GithubToken: ${{ secrets.githubtoken}}
      
