# This workflow will build and push a Docker container to an Azure Web App when a commit is pushed to your default branch.
#

name: Build and deploy a trips container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: openhackyvs74zq0trips
  BASEIMAGETAG: ${{github.sha}}
  ACRNAME: openhackyvs74zq0acr.azurecr.io
  GITOHTEAMDIRPATH: .
  RESOURCE_GROUP: openhackyvs74zq0rg
on:
  push:
    branches:
      - $default-branch
    paths: 
      - 'apis/trips/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build and push container to ACR
        run: |
          echo "Building API-TRIPS image..."
          echo "Changing directory to $GITOHTEAMDIRPATH/apis/trips..."
          cd "$GITOHTEAMDIRPATH/apis/trips"
          az acr build --image "devopsoh/api-trips:${BASEIMAGETAG}" --registry $ACRNAME --file Dockerfile .
      
#<Azure Container Registry URI>/<ACR_repository_name>:<Revision Number> where the ACR_repository_name follows the naming convention devopsoh/<image_name>:<tag>.
#openhackyvs74zq0acr.azurecr.io/devopsoh/api-poi:

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Debug'
      run: |
          echo "Deploying ${{ env.ACRNAME }}/devopsoh/api-trips:${{ env.BASEIMAGETAG }}"
    - name: 'Deploy to Azure Web App for Container'
      id: deploy-staging
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        images: ${{ env.ACRNAME }}/devopsoh/api-trips:${{ env.BASEIMAGETAG }}
        slot-name: 'staging'
    # check
    - uses: actions/checkout@v2
    - name: 'Check staging deployment is successful'
      run: |
        echo "Running polling.sh from $GITOHTEAMDIRPATH/resources/polling.sh"
        cd "$GITOHTEAMDIRPATH/resources"
        # make file runnable
        chmod +x "./polling.sh"
        ./polling.sh "${{ steps.deploy-staging.outputs.webapp-url }}/api/healthcheck/trips" 90
      shell: bash
    # if successful swap stage to prod
    - name: 'Swap web app deployment slots for blue/green'
      id: swap-to-prod
      run: |
        az webapp deployment slot swap -g ${{env.RESOURCE_GROUP}}  -n ${{ env.AZURE_WEBAPP_NAME }} --slot staging --target-slot production